// Writes the translations in Localization/<Table>.json as the Localizable.strings the bundles carry: Localization/App.json into
// App/Resources/<language>.lproj, Localization/<Module>.json into Modules/<Module>/Bundle/<language>.lproj. Assemble.sh copies them
// into the app and each module's bundle.
//
//     swift Scripts/Localize.swift
//     swift Scripts/Localize.swift --check     # also builds with the compiler's string extraction and lists texts no table has
//
// Each table maps an English text, exactly as the code has it ("Free up to %@"), to its translations in the order of `languages`.
// A translation must keep the text's placeholders (%@, %lld, %%), or the script stops. English gets an empty table: its texts are
// the keys themselves, and without an en.lproj a bundle would pick another language for someone who prefers English.

import Foundation

let languages = ["pt-BR", "fr", "es", "de"]
let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let source = root.appendingPathComponent("Localization")

func placeholders(_ text: String) -> [String] {
    let pattern = try! NSRegularExpression(pattern: "%(?:%|@|lld|llu|ld|d|lf|f)")
    return pattern.matches(in: text, range: NSRange(text.startIndex..., in: text)).map { String(text[Range($0.range, in: text)!]) }.sorted()
}

func escaped(_ text: String) -> String {
    text.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"").replacingOccurrences(of: "\n", with: "\\n")
}

var problems: [String] = []
let tables = try FileManager.default.contentsOfDirectory(at: source, includingPropertiesForKeys: nil).filter { $0.pathExtension == "json" }
for file in tables.sorted(by: { $0.lastPathComponent < $1.lastPathComponent }) {
    let name = file.deletingPathExtension().lastPathComponent
    let entries = try JSONSerialization.jsonObject(with: Data(contentsOf: file)) as! [String: [String]]
    let destination = name == "App" ? root.appendingPathComponent("App/Resources") : root.appendingPathComponent("Modules/\(name)/Bundle")
    guard FileManager.default.fileExists(atPath: destination.path) else { problems.append("\(name): no \(destination.path)"); continue }
    for (key, translations) in entries {
        if translations.count != languages.count { problems.append("\(name): \"\(key)\" has \(translations.count) translations") }
        for (language, translation) in zip(languages, translations) where placeholders(translation) != placeholders(key) {
            problems.append("\(name) \(language): \"\(translation)\" does not keep the placeholders of \"\(key)\"")
        }
    }
    for (index, language) in (["en"] + languages).enumerated() {
        let folder = destination.appendingPathComponent("\(language).lproj")
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        var lines = ["/* Generated by Scripts/Localize.swift from Localization/\(name).json. Edit that file, not this one. */", ""]
        if index > 0 {
            for key in entries.keys.sorted() {
                lines.append("\"\(escaped(key))\" = \"\(escaped(entries[key]![index - 1]))\";")
            }
        }
        try (lines.joined(separator: "\n") + "\n").write(to: folder.appendingPathComponent("Localizable.strings"), atomically: true, encoding: .utf8)
    }
    print("\(name): \(entries.count) texts in \(languages.joined(separator: ", "))")
}

// Every text the code shows, as the compiler extracts it (SwiftUI literals, String(localized:), the modules' loc(...)), must be in its
// table. Developer-only views (the design tools, the debug remote), the CLI and the helper are not translated.
if CommandLine.arguments.contains("--check") {
    let output = FileManager.default.temporaryDirectory.appendingPathComponent("macspace-strings-\(UUID().uuidString)")
    try FileManager.default.createDirectory(at: output, withIntermediateDirectories: true)
    let build = Process()
    build.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    build.arguments = ["swift", "build", "--scratch-path", output.appendingPathComponent("build").path,
                       "-Xswiftc", "-emit-localized-strings", "-Xswiftc", "-emit-localized-strings-path", "-Xswiftc", output.path]
    try build.run()
    build.waitUntilExit()
    guard build.terminationStatus == 0 else { print("error: the build failed"); exit(1) }
    let skipped = ["App/Debug/", "App/Shell/ColorLab.swift", "App/Settings/ColorLabView.swift", "App/Shell/Shading.swift", "App/Shell/Design.swift",
                   "Cli/", "Helper/", "Tests/"]
    var known: [String: Set<String>] = [:]
    for file in tables {
        let entries = try JSONSerialization.jsonObject(with: Data(contentsOf: file)) as! [String: [String]]
        known[file.deletingPathExtension().lastPathComponent] = Set(entries.keys)
    }
    let files = try FileManager.default.contentsOfDirectory(at: output, includingPropertiesForKeys: nil).filter { $0.pathExtension == "stringsdata" }
    for file in files {
        let data = try JSONSerialization.jsonObject(with: Data(contentsOf: file)) as! [String: Any]
        let path = (data["source"] as! String).replacingOccurrences(of: root.path + "/", with: "")
        guard !skipped.contains(where: path.hasPrefix) else { continue }
        let table = path.hasPrefix("Modules/") ? String(path.split(separator: "/")[1]) : "App"
        for case let entries as [[String: Any]] in (data["tables"] as! [String: Any]).values {
            for entry in entries {
                let key = entry["key"] as! String
                // Formats with no words to translate ("%@ · %@") read the same in every language.
                guard key.replacingOccurrences(of: "%@", with: "").replacingOccurrences(of: "%lld", with: "").range(of: "[A-Za-z]{2}", options: .regularExpression) != nil,
                      known[table]?.contains(key) != true else { continue }
                problems.append("\(table): \"\(key)\" (\(path)) has no translation")
            }
        }
    }
    try? FileManager.default.removeItem(at: output)
}

if !problems.isEmpty {
    FileHandle.standardError.write((problems.joined(separator: "\n") + "\n").data(using: .utf8)!)
    exit(1)
}
